<?php

/**
 * Return true if the page is being displayed inside an iframe (?display=iframe).
 */
function inside_iframe() {
  return (isset($_GET['display']) and $_GET['display'] == 'iframe');
}

/**
 * Implements hook_init().
 */
function inside_iframe_init() {
  // If the page is being displayed inside an iframe (?display=iframe)
  // call hook_inside_iframe() functions.
  if (inside_iframe()) {
    module_invoke_all('inside_iframe');
  }
}

/**
 * Implements hook_inside_iframe().
 */
function inside_iframe_inside_iframe() {
  $path = drupal_get_path('module', 'inside_iframe');
  drupal_add_css($path . '/inside_iframe.css');
}

/**
 * Implements hook_url_outbound_alter().
 * Append to url '?display=iframe' if the page is inside an iframe.
 */
function inside_iframe_url_outbound_alter(&$path, &$options, $original_path) {
  // If we are not inside an iframe, there is nothing to do.
  if (!inside_iframe())  return;

  // Don't modify the query of an absolute url.
  if (isset($options['absolute']) and $options['absolute']==TRUE)  return;

  // If a link is external, it should be opened in a new tab/window.
  if (isset($options['external']) and $options['external']==TRUE) {
    if (!isset($options['attributes']['target'])) {
      $options['attributes']['target'] = '_blank';
    }
  }

  // If the link will open in a new tab/window, then don't modify its query.
  if (isset($options['attributes']['target'])
    and $options['attributes']['target'] != '_self') {
    return;
  }

  // Modify the query by adding display=iframe
  $options['query']['display'] = 'iframe';
}

/**
 * Implements hook_drupal_goto_alter().
 * Append to url '?display=iframe' if the page is inside an iframe.
 */
function inside_iframe_drupal_goto_alter(&$path, &$options, &$http_response_code) {
  // If we are not inside an iframe, there is nothing to do.
  if (!inside_iframe())  return;

  // Don't modify the query of an absolute url.
  if (isset($options['absolute']) and $options['absolute']==TRUE)  return;

  // If a link is external, it should be opened in a new tab/window.
  if (isset($options['external']) and $options['external']==TRUE) {
    if (!isset($options['attributes']['target'])) {
      $options['attributes']['target'] = '_blank';
    }
  }

  // If the link will open in a new tab/window, then don't modify its query.
  if (isset($options['attributes']['target'])
    and $options['attributes']['target'] != '_self') {
    return;
  }

  // Modify the query by adding display=iframe
  $options['query']['display'] = 'iframe';
}
